# Support Vector Machine (SVM)

## Importing the libraries

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [7]:
data = pd.read_csv("Data.csv")
data.head()

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0             1000025                5                        1   
1             1002945                5                        4   
2             1015425                3                        1   
3             1016277                6                        8   
4             1017023                4                        1   

   Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                         1                  1                            2   
1                         4                  5                            7   
2                         1                  1                            2   
3                         8                  1                            3   
4                         1                  3                            2   

   Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0            1                3                1        1      2  
1           10                3                2        1      2  
2            2                3                1        1      2  
3            4                3                7        1      2  
4            1                3                1        1      2

In [8]:
X=data.iloc[: , :-1].values
y = data.iloc[: , -1].values

In [9]:
from sklearn.model_selection import train_test_split

X_train , X_test , y_train , y_test  = train_test_split(X , y , test_size=0.25 , random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

In [14]:
print(X_train[1,:])

[ 0.03390689  1.27578287 -0.04290763  1.63138773  0.06811505  0.3404019
  1.53244024  1.82407819  1.94996317  3.74830911]


In [21]:
from sklearn.svm import SVC

svc = SVC(kernel="rbf", degree=3 , random_state=0)
svc.fit(X_train , y_train)

SVC(random_state=0)

In [22]:
y_pred = svc.predict(X_test)
print(y_pred)

[2 2 4 4 2 2 2 4 2 2 4 2 4 2 2 4 4 4 4 2 2 2 4 2 4 4 2 2 2 4 2 4 4 2 2 2 4
 4 2 4 2 2 2 2 2 2 2 4 2 2 4 2 4 2 2 2 4 4 2 4 2 2 2 2 2 2 2 2 4 4 2 2 2 2
 2 2 4 2 2 2 4 2 4 2 2 4 2 4 4 2 4 2 4 4 2 4 4 4 4 2 2 2 4 4 2 2 4 4 2 2 4
 2 2 4 2 2 2 4 2 2 2 4 2 2 4 4 2 4 2 4 4 2 4 2 2 4 2 4 2 2 2 4 2 2 2 4 4 2
 4 2 4 2 2 2 2 2 4 4 2 4 4 4 4 2 4 2 2 2 2 2 2]


In [23]:
from sklearn.metrics import confusion_matrix , accuracy_score

cm=confusion_matrix(y_pred , y_test)
print(cm)
print(accuracy_score(y_pred , y_test))

[[101   3]
 [  6  61]]
0.9473684210526315


Generator


In [25]:
degrees = [1,2,3,4,5,6]

for i in degrees:
    svc = SVC(kernel="rbf", degree=i , random_state=0)
    svc.fit(X_train , y_train)
    y_pred = svc.predict(X_test)

    print("For degree = ",i)
    cm=confusion_matrix(y_pred , y_test)
    print(cm)
    print(accuracy_score(y_pred , y_test))


    

For degree =  1
[[102   5]
 [  5  59]]
0.9415204678362573
For degree =  2
[[102   5]
 [  5  59]]
0.9415204678362573
For degree =  3
[[102   5]
 [  5  59]]
0.9415204678362573
For degree =  4
[[102   5]
 [  5  59]]
0.9415204678362573
For degree =  5
[[102   5]
 [  5  59]]
0.9415204678362573
For degree =  6
[[102   5]
 [  5  59]]
0.9415204678362573
