In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

2023-07-24 13:09:14.204695: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [2]:
# import the data set
df = pd.read_csv("Churn_Modelling.csv")

In [3]:
#Show the dataset
X = df.iloc[:, 3:-1].values
y = df.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [4]:
#convert categorical features to label  encoded features
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
# print after changes of lavel encoding 
print(X[0:10,:])

[[619 'France' 0 42 2 0.0 1 1 1 101348.88]
 [608 'Spain' 0 41 1 83807.86 1 0 1 112542.58]
 [502 'France' 0 42 8 159660.8 3 1 0 113931.57]
 [699 'France' 0 39 1 0.0 2 0 0 93826.63]
 [850 'Spain' 0 43 2 125510.82 1 1 1 79084.1]
 [645 'Spain' 1 44 8 113755.78 2 1 0 149756.71]
 [822 'France' 1 50 7 0.0 2 1 1 10062.8]
 [376 'Germany' 0 29 4 115046.74 4 1 0 119346.88]
 [501 'France' 1 44 4 142051.07 2 0 1 74940.5]
 [684 'France' 1 27 2 134603.88 1 1 1 71725.73]]


In [6]:
# one hot encoding now 
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

# encode is name of transformer
# onehotencoder is type of transformer 
# [1] is column to transofmr
# passthrough says whatver else , keep as it is
ct = ColumnTransformer(transformers=[('onehotencoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X[0:10,:])


ImportError: cannot import name 'ColumnTransformer' from 'sklearn.preprocessing' (/Users/akashnandan/Library/Python/3.11/lib/python/site-packages/sklearn/preprocessing/__init__.py)

In [50]:
# Split to test , train , validation sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0) 

Training dataset  (8000, 14)


In [52]:
print("Og dataset ",X.shape)
print("Training dataset ",X_train.shape)
print("Test dataset ",X_test.shape)

Og dataset  (10000, 14)
Training dataset  (8000, 14)
Test dataset  (2000, 14)


In [53]:
# Scaling features
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [55]:
print(X_train[0:10,:])

[[ 0.5698444  -0.5698444   0.5698444  -1.01460667  1.74309049  0.16958176
  -1.09168714 -0.46460796  0.00666099 -1.21571749  0.8095029   0.64259497
  -1.03227043  1.10643166]
 [-1.75486502  1.75486502 -1.75486502 -1.01460667 -0.57369368 -2.30455945
   0.91601335  0.30102557 -1.37744033 -0.00631193 -0.92159124  0.64259497
   0.9687384  -0.74866447]
 [ 0.5698444  -0.5698444   0.5698444   0.98560362 -0.57369368 -1.19119591
  -1.09168714 -0.94312892 -1.031415    0.57993469 -0.92159124  0.64259497
  -1.03227043  1.48533467]
 [ 0.5698444  -0.5698444   0.5698444  -1.01460667  1.74309049  0.03556578
   0.91601335  0.10961719  0.00666099  0.47312769 -0.92159124  0.64259497
  -1.03227043  1.27652776]
 [ 0.5698444  -0.5698444   0.5698444  -1.01460667  1.74309049  2.05611444
  -1.09168714  1.73658844  1.04473698  0.8101927   0.8095029   0.64259497
   0.9687384   0.55837842]
 [-1.75486502  1.75486502 -1.75486502 -1.01460667 -0.57369368  1.29325423
  -1.09168714 -0.17749539 -1.031415    0.44253504  

In [59]:
#Building ANN 
ann = tf.keras.models.Sequential()

ann.add(tf.keras.layers.Dense(units=10 , activation='relu'))
ann.add(tf.keras.layers.Dense(units=20 , activation='relu'))
ann.add(tf.keras.layers.Dense(units=1 , activation='sigmoid'))

In [60]:
#compile the ann

ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [61]:
#train the model by fitting to dataset
ann.fit(X_train,y_train,epochs=100,batch_size=32)

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.5344 - accuracy: 0.7584
Epoch 2/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4387 - accuracy: 0.8023
Epoch 3/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4154 - accuracy: 0.8156
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3958 - accuracy: 0.8281
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3755 - accuracy: 0.8420
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3644 - accuracy: 0.8444
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3585 - accuracy: 0.8497
Epoch 8/100
250/250 [==============================] - 1s 2ms/step - loss: 0.3545 - accuracy: 0.8530
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3520 - accuracy: 0.8534
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3501 - accura

In [78]:
def predictCategory(probability):
    if probability <0.5:
        print("Will Not Exit")
    else:
        print("Will Exit")

In [85]:
print("train dataset prediction :")
print(X_train[1:2,:].shape)
# print(X_test.shape)
predictCategory(ann.predict(X_train[1:2,:])[0][0])
print("train dataset actual :")
predictCategory(y_train[0])

train dataset prediction
(1, 14)
1/1 [==============================] - 0s 30ms/step
Will Not Exit
train dataset actual
Will Not Exit


In [87]:

y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)

#why reshape???
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [89]:
#confusion matrix 

from sklearn.metrics import confusion_matrix, accuracy_score 
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1507   88]
 [ 187  218]]


0.8625

In [ ]:
truePositive = cm[0][0]
falsePositive = cm[0][1]
falseNegative = cm[0][1]
print("precision =",truePositive/(truePositive+falsePositive))
print("recall =",truePositive/(truePositive+falseNegative))